/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorDashboardRouteImport } from './routes/vendor/dashboard'
import { Route as VendorVendorIdRouteImport } from './routes/vendor/$vendorId'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as VendorProductsNewRouteImport } from './routes/vendor/products/new'
import { Route as VendorProductsProductIdRouteImport } from './routes/vendor/products/$productId'
import { Route as VendorOrdersOrderIdRouteImport } from './routes/vendor/orders/$orderId'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorIdRoute = VendorVendorIdRouteImport.update({
  id: '/vendor/$vendorId',
  path: '/vendor/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/vendor/products/new',
  path: '/vendor/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsProductIdRoute = VendorProductsProductIdRouteImport.update({
  id: '/vendor/products/$productId',
  path: '/vendor/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersOrderIdRoute = VendorOrdersOrderIdRouteImport.update({
  id: '/vendor/orders/$orderId',
  path: '/vendor/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  id:
    | '__root__'
    | '/'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  VendorVendorIdRoute: typeof VendorVendorIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorOrdersOrderIdRoute: typeof VendorOrdersOrderIdRoute
  VendorProductsProductIdRoute: typeof VendorProductsProductIdRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$vendorId': {
      id: '/vendor/$vendorId'
      path: '/vendor/$vendorId'
      fullPath: '/vendor/$vendorId'
      preLoaderRoute: typeof VendorVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/vendor/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products/$productId': {
      id: '/vendor/products/$productId'
      path: '/vendor/products/$productId'
      fullPath: '/vendor/products/$productId'
      preLoaderRoute: typeof VendorProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders/$orderId': {
      id: '/vendor/orders/$orderId'
      path: '/vendor/orders/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof VendorOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRouteWithChildren,
  VendorVendorIdRoute: VendorVendorIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorOrdersOrderIdRoute: VendorOrdersOrderIdRoute,
  VendorProductsProductIdRoute: VendorProductsProductIdRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
