/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeVendorRouteImport } from './routes/become-vendor'
import { Route as BecomeAdminRouteImport } from './routes/become-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorSettingsRouteImport } from './routes/vendor/settings'
import { Route as VendorDashboardRouteImport } from './routes/vendor/dashboard'
import { Route as VendorVendorIdRouteImport } from './routes/vendor/$vendorId'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as VendorProductsNewRouteImport } from './routes/vendor/products/new'
import { Route as VendorProductsProductIdRouteImport } from './routes/vendor/products/$productId'
import { Route as VendorOrdersOrderIdRouteImport } from './routes/vendor/orders/$orderId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeVendorRoute = BecomeVendorRouteImport.update({
  id: '/become-vendor',
  path: '/become-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAdminRoute = BecomeAdminRouteImport.update({
  id: '/become-admin',
  path: '/become-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorIdRoute = VendorVendorIdRouteImport.update({
  id: '/vendor/$vendorId',
  path: '/vendor/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/vendor/products/new',
  path: '/vendor/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsProductIdRoute = VendorProductsProductIdRouteImport.update({
  id: '/vendor/products/$productId',
  path: '/vendor/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersOrderIdRoute = VendorOrdersOrderIdRouteImport.update({
  id: '/vendor/orders/$orderId',
  path: '/vendor/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-admin': typeof BecomeAdminRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-admin': typeof BecomeAdminRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-admin': typeof BecomeAdminRoute
  '/become-vendor': typeof BecomeVendorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/vendor/$vendorId': typeof VendorVendorIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/orders/$orderId': typeof VendorOrdersOrderIdRoute
  '/vendor/products/$productId': typeof VendorProductsProductIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-admin'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/verify-email'
    | '/admin/admins'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/vendors'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/settings'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-admin'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/verify-email'
    | '/admin/admins'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/vendors'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/settings'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  id:
    | '__root__'
    | '/'
    | '/become-admin'
    | '/become-vendor'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/orders'
    | '/products'
    | '/profile'
    | '/register'
    | '/verify-email'
    | '/admin/admins'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/vendors'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/vendor/$vendorId'
    | '/vendor/dashboard'
    | '/vendor/settings'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$productId'
    | '/vendor/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAdminRoute: typeof BecomeAdminRoute
  BecomeVendorRoute: typeof BecomeVendorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  VendorVendorIdRoute: typeof VendorVendorIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorOrdersOrderIdRoute: typeof VendorOrdersOrderIdRoute
  VendorProductsProductIdRoute: typeof VendorProductsProductIdRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-vendor': {
      id: '/become-vendor'
      path: '/become-vendor'
      fullPath: '/become-vendor'
      preLoaderRoute: typeof BecomeVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-admin': {
      id: '/become-admin'
      path: '/become-admin'
      fullPath: '/become-admin'
      preLoaderRoute: typeof BecomeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$vendorId': {
      id: '/vendor/$vendorId'
      path: '/vendor/$vendorId'
      fullPath: '/vendor/$vendorId'
      preLoaderRoute: typeof VendorVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/vendor/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products/$productId': {
      id: '/vendor/products/$productId'
      path: '/vendor/products/$productId'
      fullPath: '/vendor/products/$productId'
      preLoaderRoute: typeof VendorProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders/$orderId': {
      id: '/vendor/orders/$orderId'
      path: '/vendor/orders/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof VendorOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAdminRoute: BecomeAdminRoute,
  BecomeVendorRoute: BecomeVendorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  VendorVendorIdRoute: VendorVendorIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorOrdersOrderIdRoute: VendorOrdersOrderIdRoute,
  VendorProductsProductIdRoute: VendorProductsProductIdRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
